version: '3'

volumes:
  local_postgres17_data: {}
  local_postgres17_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: expfactory_deploy_local_django
    container_name: django
    depends_on:
      - postgres
      - q2worker
    volumes:
      - .:/app:z
      - ./expfactory_deploy_local/src/expfactory_deploy_local/static/:/app/deployment_assets/non_repo_files/default/static/:rw
      - ${EXPFACTORY_EXPERIMENTS_PATH:-./deployment_assets/repos/expfactory-experiments}:/app/deployment_assets/repos/expfactory-experiments:rw
      - ${EXPFACTORY_EXPERIMENTS_PATH:-./deployment_assets/repos/expfactory-experiments}:/app/deployment_assets/non_repo_files/default/static/experiments/:ro
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
      - "4000:4000"
    command: /start
    develop:
      watch:
        - action: restart
          path: ./expfactory_deploy

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: expfactory_deploy_production_postgres
    container_name: postgres
    volumes:
      - local_postgres17_data:/var/lib/postgresql/data:Z
      - local_postgres17_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./compose/local/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app:z
      - ./expfactory_deploy_local/src/expfactory_deploy_local/static/:/app/deployment_assets/non_repo_files/default/static/:rw
      - ${EXPFACTORY_EXPERIMENTS_PATH:-./deployment_assets/repos/expfactory-experiments}:/app/deployment_assets/non_repo_files/default/static/experiments/:ro
    depends_on:
      - django

  q2worker:
    <<: *django
    image: expfactory_deploy_local_q2_worker
    container_name: q2worker
    depends_on:
      - postgres
    ports: []
    command: /start_django_q2

  docs:
    image: expfactory_deploy_local_docs
    container_name: docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./expfactory_deploy:/app/expfactory_deploy:z
    ports:
      - "7000:7000"
    command: /start-docs

#
#  #mailhog:
#  #  image: mailhog/mailhog:v1.0.0
#  #  container_name: mailhog
#  #  ports:
#  #    - "8025:8025"
#
#  redis:
#    image: redis:5.0
#    container_name: redis
#
#  celeryworker:
#    <<: *django
#    image: expfactory_deploy_local_celeryworker
#    container_name: celeryworker
#    depends_on:
#      - redis
#      - postgres
#    ports: []
#    command: /start-celeryworker
#
#  celerybeat:
#    <<: *django
#    image: expfactory_deploy_local_celerybeat
#    container_name: celerybeat
#    depends_on:
#      - redis
#      - postgres
#    ports: []
#    command: /start-celerybeat
#
#  flower:
#    <<: *django
#    image: expfactory_deploy_local_flower
#    container_name: flower
#    ports:
#      - "5555:5555"
#    command: /start-flower
