# Generated by Django 4.1.3 on 2023-08-01 09:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("experiments", "0035_remove_subject_mturk_id_assignment_group_index_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimpleCC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("completion_url", models.URLField(blank=True, max_length=65536)),
                (
                    "battery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="experiments.battery",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
