# Generated by Django 4.1.3 on 2023-08-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prolific", "0002_study_studycollection_studysubject_studyrank_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="rank",
            field=models.IntegerField(default=0, verbose_name="Experiment order"),
        ),
    ]
