# Generated by Django 4.1.3 on 2023-09-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prolific", "0005_rename_default_project_studycollection_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studycollection",
            name="reward",
            field=models.IntegerField(default=0),
        ),
    ]
