# Generated by Django 4.1.3 on 2023-09-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prolific", "0006_studycollection_reward"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="participant_group",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studycollection",
            name="workspace_id",
            field=models.TextField(blank=True),
        ),
    ]
