# Generated by Django 4.1.3 on 2023-09-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prolific", "0007_study_participant_group_studycollection_workspace_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="studycollection",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
