# Generated by Django 4.1.3 on 2023-09-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prolific", "0008_studycollection_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="studycollection",
            name="inter_study_delay",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studycollection",
            name="name",
            field=models.TextField(blank=True, help_text="Name internal to expfactory"),
        ),
        migrations.AlterField(
            model_name="studycollection",
            name="title",
            field=models.TextField(
                blank=True,
                help_text="Base Title to be used by all stutdies in collection",
            ),
        ),
    ]
