# Generated by Django 4.1.3 on 2023-10-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prolific", "0009_studycollection_inter_study_delay_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studycollection",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="studycollection",
            name="estimated_completion_time",
            field=models.IntegerField(default=0, help_text="Value in minutes."),
        ),
        migrations.AlterField(
            model_name="studycollection",
            name="name",
            field=models.TextField(
                blank=True, help_text="Name internal to expfactory."
            ),
        ),
        migrations.AlterField(
            model_name="studycollection",
            name="project",
            field=models.TextField(
                blank=True,
                help_text="Prolific project ID for the studies to be created under.",
            ),
        ),
        migrations.AlterField(
            model_name="studycollection",
            name="reward",
            field=models.IntegerField(default=0, help_text="Value in cents."),
        ),
        migrations.AlterField(
            model_name="studycollection",
            name="title",
            field=models.TextField(
                blank=True,
                help_text="Base Title to be used by all stutdies in collection on Prolific.",
            ),
        ),
    ]
