# Generated by Django 4.1.3 on 2023-11-13 21:05

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("prolific", "0010_studycollection_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("prolific_id", models.TextField(unique=True)),
                ("active", models.BooleanField(default=True)),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
