# Generated by Django 4.1.3 on 2023-11-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prolific", "0011_blockedparticipant"),
    ]

    operations = [
        migrations.AddField(
            model_name="studycollection",
            name="number_of_groups",
            field=models.IntegerField(
                default=0,
                help_text="\n            Number of different groups to randomly assign participants to.\n            A participants group number is injected into serve experiment template for use by experiments.\n            0 means nothing will be added to the context.\n        ",
            ),
        ),
        migrations.AddField(
            model_name="studycollectionsubject",
            name="group_index",
            field=models.IntegerField(default=0),
        ),
    ]
