# Generated by Django 4.1.3 on 2024-01-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prolific", "0012_studycollection_number_of_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studysubject",
            name="prolific_session_id",
            field=models.TextField(blank=True),
        ),
    ]
