# Generated by Django 4.1.3 on 2024-03-05 17:46

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("prolific", "0014_studycollection_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="studycollection",
            name="collection_grace_interval",
            field=models.DurationField(
                blank=True,
                help_text="Time after warning message is sent to kick participant from remaining studies.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studycollection",
            name="collection_kick_on_timeout",
            field=models.BooleanField(
                default=False,
                help_text="If True kick participant after the expiration of grace period from having not completed all studies.",
            ),
        ),
        migrations.AddField(
            model_name="studycollection",
            name="collection_time_to_warning",
            field=models.DurationField(
                blank=True,
                help_text="Overall time participant has to complete all studies before recieving a warning message.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studycollection",
            name="collection_warning_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studycollection",
            name="study_grace_interval",
            field=models.DurationField(
                blank=True,
                help_text="Time after warning message has been sent to kick participant from the study.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studycollection",
            name="study_kick_on_timeout",
            field=models.BooleanField(
                default=False,
                help_text="If True kick participant after a expiration of grace period if they have not started the study.",
            ),
        ),
        migrations.AddField(
            model_name="studycollection",
            name="study_time_to_warning",
            field=models.DurationField(
                blank=True,
                help_text="After completing a study participants will be reminded to start on the next study after this amount of time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studycollection",
            name="study_warning_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studycollection",
            name="time_to_start_first_study",
            field=models.DurationField(
                blank=True,
                help_text="Upon adding participant to a study collection, they have this long to start the first study before being removed from study",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studycollectionsubject",
            name="failed_at",
            field=model_utils.fields.MonitorField(
                default=None,
                monitor="status",
                null=True,
                when={"flagged", "failed", "kicked"},
            ),
        ),
        migrations.AddField(
            model_name="studycollectionsubject",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[
                    ("n/a", "n/a"),
                    ("not-started", "not-started"),
                    ("started", "started"),
                    ("completed", "completed"),
                    ("failed", "failed"),
                    ("redo", "redo"),
                    ("kicked", "kicked"),
                    ("flagged", "flagged"),
                ],
                default="n/a",
                max_length=100,
                no_check_for_status=True,
            ),
        ),
        migrations.AddField(
            model_name="studycollectionsubject",
            name="warned_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
