# Generated by Django 4.1.3 on 2024-03-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prolific", "0015_studycollection_collection_grace_interval_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studycollectionsubject",
            name="warned_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
