# Generated by Django 4.1.3 on 2024-03-19 17:38

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("prolific", "0019_studycollectionsubject_current_study_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studycollectionsubject",
            name="status_reason",
            field=model_utils.fields.StatusField(
                choices=[
                    ("n/a", "n/a"),
                    ("study-timer", "study-timer"),
                    ("initial-timer", "initial-timer"),
                    ("collection-timer", "collection-timer"),
                ],
                default="n/a",
                max_length=100,
                no_check_for_status=True,
            ),
        ),
        migrations.AlterField(
            model_name="studycollectionsubject",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[
                    ("n/a", "n/a"),
                    ("not-started", "not-started"),
                    ("started", "started"),
                    ("completed", "completed"),
                    ("failed", "failed"),
                    ("redo", "redo"),
                    ("kicked", "kicked"),
                    ("flagged", "flagged"),
                ],
                default="n/a",
                max_length=100,
                no_check_for_status=True,
            ),
        ),
    ]
