# Generated by Django 4.1.3 on 2024-03-25 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prolific", "0023_studycollection_failure_to_strat_grace_interval_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studycollection",
            old_name="failure_to_strat_grace_interval",
            new_name="failure_to_start_grace_interval",
        ),
    ]
