# Generated by Django 4.1.3 on 2024-03-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "prolific",
            "0024_rename_failure_to_strat_grace_interval_studycollection_failure_to_start_grace_interval",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="studycollectionsubject",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Used to manually prevent subject from progressing in study.",
            ),
        ),
        migrations.AddField(
            model_name="studysubject",
            name="added_to_study",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
