# Generated by Django 4.1.3 on 2024-09-11 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("prolific", "0025_studycollectionsubject_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prolificapiresult",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="prolific.studycollection",
            ),
        ),
    ]
