# Generated by Django 5.1.4 on 2025-09-10 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prolific", "0026_alter_prolificapiresult_collection"),
    ]

    operations = [
        migrations.CreateModel(
            name="Taskflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taskflow_remote_id", models.TextField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="studycollection",
            name="taskflow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="prolific.taskflow",
            ),
        ),
    ]
