#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput


/usr/local/bin/gunicorn config.asgi --bind 0.0.0.0:5000 --chdir=/app -w 4 --max-requests 2000 -t 60 --graceful-timeout 60 -k uvicorn.workers.UvicornWorker
