# Generated by Django 4.1.3 on 2023-11-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultqa",
            name="feedback",
            field=models.TextField(blank=True),
        ),
    ]
